services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: senhafodastica
    volumes:
      - mongo_home:/var/mongo_home
    ports:
      - 5432:5432
    networks:
      - mongo_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo_home:

